spring:
  application:
    name: material_management_system_base_web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:8806/material_management_system?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=GMT%2B8
    username: root
    password: 123
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  tomcat:
    max-http-form-post-size: 90000
    uri-encoding: utf-8
    max-connections: 30000
    connection-timeout: 20000
  port: 8888

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/*/*.xml
  type-aliases-package: com.lda.system.entity
alioss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4G36sFnQ5Gk93q29HTr6
  accessKeySecret: PxXtjf5FSvUUJgJyMkDJbWYM1kfmRI
  bucketName: material-management-system